<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-1J6Q2U8" failures="2" tests="2" name="Test(failed)" time="0.063" errors="0" timestamp="2025-05-29T12:11:13 IST">
  <testcase classname="com.example.tests.Retry_Testcases" name="Testcase02" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.example.tests.Retry_Testcases.Testcase02(Retry_Testcases.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Testcase02 -->
  <testcase classname="com.example.tests.Retry_Testcases" name="Testcase01" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.example.tests.Retry_Testcases.Testcase01(Retry_Testcases.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Testcase01 -->
  <testcase classname="com.example.tests.Retry_Testcases" name="Testcase03" time="0.0">
    <ignored/>
  </testcase> <!-- Testcase03 -->
</testsuite> <!-- Test(failed) -->
